### ISSUE TITLE
Can I safely disable this?

### ISSUE THREAD

**Issue by te-je** [easy-webpack/config-fonts-and-images#5]
It seems that when I turn this off in `webpack.config.js` all my image sources turn to [object Object]. Is there something else that I need to be doing?

**Comment by niieani** [comment]
If you don't "import" any fonts in your CSS or HTML templates, you can disable this. Otherwise, you need it to keep those files in the dependency graph, unless you add your own loaders.
All it does is: https://github.com/easy-webpack/config-fonts-and-images/blob/master/src/index.ts.
